### ISSUE TITLE
Use more concise naming conventions by removing redundant words

### ISSUE THREAD

**Issue by wellu** [gavinlyonsrepo/HD44780_LCD_PCF8574#3]
Library works ok, tested on (clone) Uno and 16 x 2 display so great functionality wise. A little improvement though.

I find function naming conventions a bit too explicit though e.g 

`lcd.PCF8574_LCDResetScreen(HD44780LCD::LCDCursorTypeOff);`

or 

`lcd.PCF8574_LCDSendString("Hello World!");`

as I see lot of redundant _PCF8574_ and _LCD_ words here. Could be simply

`lcd.write("Hello World!");`

or

`lcd.reset(HD44780LCD::CursorOff);`

as class HD44780LCD namespaces all within so there is no naming collisions with other writes or resets or anything else. Also calls such as 

`lcd.PCF8574_LCDGOTO(HD44780LCD::LCDLineNumberOne, 0);`

could be written in more concise way

`lcd.goto(0, 0); // goto first line, first column`

as I don't see any value of enuming lines.

Anyway, thanks for the work, works perfect.

**Comment by gavinlyonsrepo** [comment]
Hi 

I original wrote this for the PIC in C before porting it to Arduino C++ which explains the longer  function names. I should have removed the "PCF8574_" and  perhaps "LCD" .  

I don't think having verbose method names is a big deal in the age  of featured IDE's with auto-complete etc as Arduino IDE 2.0 has now. 

Having Enums instead of magic numbers for line numbers prevents user error and helps with user interface.  The line number enum is a parameter for two different methods and is used internally in code.

The library is over a year and half old now so I won't be changing it and breaking backwards compatibility at this point, for this. 

Thanks.
